imports:
    - { resource: ../test/config.yaml }
    - { resource: '@PimcoreCoreBundle/Resources/config/pimcore/prod.yml' } # loads default dev configuration
    - { resource: '../../src/CoreShop/Behat/Resources/config/services.yml' }

# this cache is used during tests when setting up pimcore
pimcore:
    cache:
        pool_service_id: pimcore.cache.core.pool.array

doctrine:
    dbal:
        connections:
            default:
                url: '%pimcore_test.db.dsn%'
                host: ~
                port: ~
                dbname: ~
                user: ~
                password: ~

parameters:
    pimcore_test.db.dsn: '%env(PIMCORE_TEST_DB_DSN)%'
    env(PIMCORE_TEST_DB_DSN): ~

framework:
    session:
        handler_id: 'Symfony\Component\HttpFoundation\Session\Storage\Handler\NullSessionHandler'
