imports:
    - { resource: "services/forms.yml" }
    - { resource: "services/installer.yml" }

services:
    _defaults:
        public: true

    ### Registries
    process_manager.registry.processes:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - ProcessManagerBundle\Process\ProcessInterface
            - 'Process Manager Processes'

    process_manager.registry.process_reports:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - ProcessManagerBundle\Report\ReportInterface
            - 'Reports'

    process_manager.registry.process_handler_factories:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - ProcessManagerBundle\Monolog\HandlerFactoryInterface
            - 'Handler Factories'

    process_manager.form.registry.processes:
        class: CoreShop\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

    ### Processes
    ProcessManagerBundle\Process\Cli:
        tags:
            - { name: process_manager.process, type: cli, form-type: ProcessManagerBundle\Form\Type\Processes\CliType }

    ProcessManagerBundle\Process\Pimcore:
        tags:
            - { name: process_manager.process, type: pimcore, form-type: ProcessManagerBundle\Form\Type\Processes\PimcoreType }

    ### Event listeners
    ProcessManagerBundle\EventListener\ArtifactDeletionListener:
        arguments:
            - '@process_manager.repository.process'
        tags:
            - { name: kernel.event_listener, event: pimcore.asset.postDelete, method: onArtifactAssetDelete }

    ### Maintenance task
    ProcessManagerBundle\Maintenance\CronTask:
        arguments:
            - '@process_manager.registry.processes'
        tags:
            - { name: pimcore.maintenance.task, type: process_manager.maintenance.cron }

    ProcessManagerBundle\Logger\ProcessLogger:
        arguments:
            - '@logger'

    ProcessManagerBundle\Monolog\ProcessProcessor:
        lazy: true
        arguments:
            - '@ProcessManagerBundle\Logger\DefaultHandlerFactory'
            - '@process_manager.registry.process_handler_factories'
        tags:
            - { name: monolog.processor }

    ProcessManagerBundle\Monolog\ProcessHandler: ~

    ProcessManagerBundle\Logger\DefaultHandlerFactory:
        arguments:
            - '%process_manager.log_directory%'

    ProcessManagerBundle\Report\DefaultReport: ~

    ### Startup Resolver
    process_manager.registry.startup_form_resolver:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - ProcessManagerBundle\Process\ProcessStartupFormResolverInterface
            - 'Process Startup Form Resolver'

    ProcessManagerBundle\Process\CompositeProcessStartupFormResolver:
        arguments:
            - '@process_manager.registry.startup_form_resolver'
